Updated project-image project-text project-specifications
Adm1RalDen/official-next-js pull request #19
Opened 2021-12-09 09:47 UTC by YuraStork

2021-12-09 09:54 UTC, Adm1RalDen commented on components/works/project/project-specifications.tsx
> +  const { technologies, duration, efforts } = props;
Дані пропси можна витягувати прямо в параметрах функції
funcName({propName1, propName2}: interface)

2021-12-09 10:12 UTC, Adm1RalDen commented on components/works/project/project-text.tsx
> +  const { hrefWeb, title, aimProject, description, disclose } = props;
аналогічно, при невеликій кількості пропсів, можна деструктуризувати прямо в паруметрах функції

2021-12-09 10:14 UTC, Adm1RalDen commented on components/works/project/project-text.tsx
> +          hrefWeb !== '' ? <a href={hrefWeb} target='_blank' className='title_a'>{title}</a> :
немає сенсу перевіряти таким способом, буде достатньо, hrefWeb ? .. : …;

2021-12-09 10:16 UTC, Adm1RalDen commented on components/works/project/project-text.tsx
> +          {!disclose ? <div className='disclose-block'>Do not disclose</div> : null}
чи можемо ми упростити логіку до !disclose &&

2021-12-09 10:18 UTC, Adm1RalDen commented on components/works/project/project.tsx
> +              <ProjectText hrefWeb={hrefWeb} title={title} aimProject={aimProject} description={description} disclose={disclose} />
При великій кількості пропсів, бажано переробити на обьект

2021-12-09 10:19 UTC, Adm1RalDen reviewed
Потрібно рефакторити

2021-12-09 11:26 UTC, Andrew01011997 requested changes

2021-12-09 11:26 UTC, Andrew01011997 commented on components/works/project/project-specifications.tsx
> +        {technologies.map((t) => <div className="item" key={t}><span>{t}</span></div>)}
unnecessary nesting

2021-12-09 11:26 UTC, Andrew01011997 commented on components/works/project/project-text.tsx
> +  hrefWeb: string;
mb siteUrl
it will be more readable

2021-12-09 11:26 UTC, Andrew01011997 commented on components/works/project/project-text.tsx
> +          hrefWeb !== '' ? <a href={hrefWeb} target='_blank' className='title_a'>{title}</a> :
title_a
i can't understand what is this
incorrect naming

2021-12-09 11:26 UTC, Andrew01011997 commented on components/works/project/project.tsx
>      <>
unnecessary wrapping

2021-12-09 12:31 UTC, Andrew01011997 requested changes

2021-12-09 12:31 UTC, Andrew01011997 commented on styles/components/works/project.scss
> +          background-color: rgb(41, 1, 1);
please use exists color variable

2021-12-09 12:31 UTC, Andrew01011997 commented on components/works/project/project-specifications.tsx
> +        {technologies.map((t) => <div className="item" key={t}><span>{t}</span></div>)}
not done yet

2021-12-09 12:31 UTC, Andrew01011997 commented on components/works/project/project-specifications.tsx
> +        {technologies.map((t) => <div className="item" key={t}><span>{t}</span></div>)}
`<div className="item" key={t}><span>{t}</span></div>`

2021-12-09 12:31 UTC, Andrew01011997 commented on components/works/project/project.tsx
>      <>
pls remove <></>

2021-12-09 12:59 UTC, YuraStork commented on styles/components/works/project.scss
> +          background-color: rgb(41, 1, 1);
color was changed on black

2021-12-09 18:03 UTC, Adm1RalDen requested changes

2021-12-09 18:03 UTC, Adm1RalDen commented on data/7opiton.ts
>      'Braintree',
remove this technology  with this project

2021-12-09 20:13 UTC, Adm1RalDen requested changes

2021-12-09 20:13 UTC, Adm1RalDen commented on styles/components/works/project.scss
> +          background-color: black;
переглянь що означає scss variable, у нас в проекті створені деякі константі значення кольорів так тому подібне

2021-12-10 12:02 UTC, Adm1RalDen approved these changes

2021-12-10 12:07 UTC, Andrew01011997 requested changes

2021-12-10 12:07 UTC, Andrew01011997 commented on components/works/project/project-image.tsx
> +  data: ProjectImageProps;
Please change it to two separated props
I think it's be better

2021-12-10 12:07 UTC, Andrew01011997 commented on components/works/project/project-specifications.tsx
> +  data: ProjectSpecificationsProps;
Same as previous
You create unnecessary object wrapper

2021-12-10 14:21 UTC, Andrew01011997 approved these changes

2021-12-10 14:51 UTC, merged